Imprement drill create. But broken.
(venv) yoka@MacBookWorld ~/multiple> python3 manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
June 02, 2019 - 16:23:15
Django version 2.1.7, using settings 'multiple.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[02/Jun/2019 16:23:28] "GET / HTTP/1.1" 200 14728
[02/Jun/2019 16:23:29] "GET /exam/ HTTP/1.1" 200 19187
[02/Jun/2019 16:23:34] "GET /drill/3539427c-9f18-44a7-844f-7ca13c7d922f/create HTTP/1.1" 200 16765
Internal Server Error: /drill/3539427c-9f18-44a7-844f-7ca13c7d922f/create
Traceback (most recent call last):
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.NotNullViolation: null value in column "created" violates not-null constraint
DETAIL:  Failing row contains (289b5444-b552-43f1-baf0-54def0bc093d, set, null, 3539427c-9f18-44a7-844f-7ca13c7d922f).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/extra_views/advanced.py", line 165, in post
    return super(BaseUpdateWithInlinesView, self).post(request, *args, **kwargs)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/extra_views/advanced.py", line 119, in post
    return self.forms_valid(form, inlines)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/extra_views/advanced.py", line 66, in forms_valid
    formset.save()
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/forms/models.py", line 669, in save
    return self.save_existing_objects(commit) + self.save_new_objects(commit)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/forms/models.py", line 803, in save_new_objects
    self.new_objects.append(self.save_new(form, commit=commit))
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/forms/models.py", line 949, in save_new
    obj.save()
  File "/Users/yoka/multiple/choice/models.py", line 173, in save
    super().save(*args, **kwargs)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1289, in execute_sql
    cursor.execute(sql, params)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 186, in execute
    return self._record(self.cursor.execute, sql, params)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/debug_toolbar/panels/sql/tracking.py", line 124, in _record
    return method(sql, params)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/yoka/multiple/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: null value in column "created" violates not-null constraint
DETAIL:  Failing row contains (289b5444-b552-43f1-baf0-54def0bc093d, set, null, 3539427c-9f18-44a7-844f-7ca13c7d922f).

[02/Jun/2019 16:23:38] "POST /drill/3539427c-9f18-44a7-844f-7ca13c7d922f/create HTTP/1.1" 500 198223